{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ml-api.fullname" . }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ml-api
      {{- include "ml-api.selectorLabels" . | nindent 6 }}

{{- end }}