apiVersion: v1
kind: Secret
metadata:
  name: hippo-pguser-coreii
  namespace: pgo
  labels:
    postgres-operator.crunchydata.com/cluster: hippo
    postgres-operator.crunchydata.com/pguser: coreii
stringData:
  password: coreii123
---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  databaseInitSQL:
    key: init.sql
    name: hippo-init-sql
  postgresVersion: 16
  users:
    - name: rhino
      databases:
        - zoo
    - name: coreii
      options: 'SUPERUSER'
      databases:
         - zoo
         - postgres
  instances:
    - name: instance1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi

  backups:
    pgbackrest:
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              accessModes:
                - 'ReadWriteOnce'
              resources:
                requests:
                  storage: 1Gi
