{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "frontend.fullname" . }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: frontend
      {{- include "frontend.selectorLabels" . | nindent 6 }}

{{- end }}