replicaCount: 1
image:
  repository: cgr.dev/chainguard/postgres
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "postgres"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  storageClassName: longhorn