apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "embedding.fullname" . }}
  labels:
    app: embedding
    {{- include "embedding.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
  selector:
    matchLabels:
      app: embedding
      {{- include "embedding.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: embedding
        {{- include "embedding.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - embedding
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: secret_key
            - name: BUCKET_NAME
              value: {{ .Values.minio.bucketName }}
            - name: VLLM_CPU_KVCACHE_SPACE
              value: "{{ .Values.vllm.kvcache_space }}"
            - name: VLLM_CPU_OMP_THREADS_BIND
              value: "{{ .Values.vllm.omp_threads_bind }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: "2Gi"
