{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.Name }}
  labels:
    app: embedding
    {{- include "embedding.labels" . | nindent 4 }}
type: Opaque
data:
  access_key: {{ .Values.secret.accessKey }}
  secret_key: {{ .Values.secret.secretKey }}
{{- end }}