all:
  hosts:
    192.168.3.44:
      ansible_user: ec2-user
      hostname: rke-worker1.labenv.ai
      ansible_host: 192.168.3.44
    192.168.2.134:
      ansible_user: ec2-user
      hostname: rke-worker2.labenv.ai
      ansible_host: 192.168.2.134
    192.168.2.226:
      ansible_user: ec2-user
      hostname: rke-server1.labenv.ai
      ansible_host: 192.168.2.226
    192.168.3.205:
      ansible_user: ec2-user
      hostname: rke-server2.labenv.ai
      ansible_host: 192.168.3.205
    192.168.3.32:
      ansible_host: 192.168.3.32
      ansible_user: ec2-user
      hostname: rke-server3.labenv.ai   
    192.168.3.186:
      ansible_host: 192.168.3.186
      ansible_user: ec2-user
      hostname: rke-lb.labenv.ai
    192.168.3.165:
      ansible_host: 192.168.3.165
      ansible_user: ec2-user
      hostname: etcd-1.labenv.ai
    192.168.2.138:
      ansible_host: 192.168.2.138
      ansible_user: ec2-user
      hostname: etcd-2.labenv.ai
    192.168.3.66:
      ansible_host: 192.168.3.66
      ansible_user: ec2-user
      hostname: etcd-3.labenv.ai
  vars:
    host_entries:
      - 192.168.3.186 rke-lb.labenv.ai
      - 192.168.2.226 rke-server1.labenv.ai
      - 192.168.3.205 rke-server2.labenv.ai
      - 192.168.3.32 rke-server3.labenv.ai
      - 192.168.3.44 rke-worker1.labenv.ai
      - 192.168.2.134 rke-worker2.labenv.ai
      - 192.168.3.165 etcd-1.labenv.ai
      - 192.168.2.138 etcd-2.labenv.ai
      - 192.168.3.66 etcd-3.labenv.ai
    kubernetes_api_server_host: "rke-lb.labenv.ai"
    kubeconfig_path: "/home/ansible/.kube/config"
    values_file_path: "/home/ansible/project/coreii/k8s/ansible/roles/argocd-install/values.yaml"
    install_rke2_version: v1.31.1+rke2r2
    # # In air-gapped envs, it might be convenient to download the tar files from custom URLs
    rke2_image_tar_urls:
    - https://github.com/rancher/rke2/releases/download/v1.31.1%2Brke2r1/rke2-images-canal.linux-amd64.tar.zst
    - https://github.com/rancher/rke2/releases/download/v1.31.1%2Brke2r1/rke2-images-core.linux-amd64.tar.zst
rke2_cluster:
  children:
    rke2_lb: 
      hosts:
        192.168.3.186:
    rke2_servers:
      hosts:
        192.168.3.165:
          rke2_config:
             disable-apiserver: true
             disable-controller-manager: true
             disable-scheduler: true
             selinux: true
             tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
        192.168.2.138:
          rke2_config:
             disable-apiserver: true
             disable-controller-manager: true
             disable-scheduler: true
             selinux: true
             tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
        192.168.3.66:
          rke2_config:
             disable-apiserver: true
             disable-controller-manager: true
             disable-scheduler: true
             selinux: true
             tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
        192.168.2.226:
          rke2_config:
            disable-etcd: true
            selinux: true
            tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
        192.168.3.205:
          rke2_config:
            disable-etcd: true
            selinux: true
            tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
        192.168.3.32:
          rke2_config:
            disable-etcd: true
            selinux: true
            tls-san:
             - rke-lb.labenv.ai
             - etcd-1.labenv.ai
             - etcd-2.labenv.ai
             - etcd-3.labenv.ai
             - rke-server1.labenv.ai
             - rke-server2.labenv.ai
             - rke-server3.labenv.ai
          node_taints:
          - CriticalAddonsOnly=true:NoSchedule
    rke2_agents:
      vars:
        rke2_config:
          node-label:
            - agentGroupLabel=true
      hosts:
        192.168.3.44:
          node_labels:
            - agent0Label=true
        192.168.2.134:
          node_labels:
            - agent1Label=true
