apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kg-api.fullname" . }}
  labels:
    {{- include "kg-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: kg-api
      {{- include "kg-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: kg-api
        {{- include "kg-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - kg-api
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ML_API_URL
              value: {{ .Values.kgApi.mlApiUrl }}
            - name: VECTOR_LENGTH
              value: "{{ .Values.kgApi.vectorLength }}"
            - name: KG_API_PORT
              value: "{{ .Values.kgApi.port }}"
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kgApi.db.secretName }}
                  key: dbname
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kgApi.db.secretName }}
                  key: port
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kgApi.db.secretName }}
                  key: host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kgApi.db.secretName }}
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kgApi.db.secretName }}
                  key: password
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 3
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
