{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  dbname: {{ .Values.secret.dbname }}
  host: {{ .Values.secret.host  }}
  jdbc-uri: {{ .Values.secret.jdbcUri  }}
  password: {{ .Values.secret.password  }}
  port: {{ .Values.secret.port  }}
  uri: {{ .Values.secret.uri  }}
  user: {{ .Values.secret.user  }}
  verifier: {{ .Values.secret.verifier }}
{{- end }}