apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-service
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: kong
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/apps/kong-service
    repoURL: 'https://github.com/01cloud/inl-infra.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
