apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-service
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: metallb-system
    server: 'https://kubernetes.default.svc'
  source:
    path: argocd/apps/metallb-service/
    repoURL: 'git@github.com:01cloud/inl-infra.git'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
