apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inference.fullname" . }}
  labels:
    {{- include "inference.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: inference
      {{- include "inference.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: inference
        {{- include "inference.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - inference
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: access_key
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.minio.secretName }}
                  key: secret_key
            - name: BUCKET_NAME
              value: {{ .Values.minio.bucketName }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10     
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 3
            periodSeconds: 5
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
