{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: minio-keys
  labels:
    app: inference
    {{- include "inference.labels" . | nindent 4 }}
type: Opaque
data:
  access_key: {{ .Values.secret.accessKey }}
  secret_key: {{ .Values.secret.secretKey }}

{{- end }}
