apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.pvc.name }}
  labels:
    {{- include "portal-db.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.pvc.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage.size }}
  storageClassName: {{ .Values.pvc.storageClassName }}
