apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "frontend-test.fullname" . }}
  labels:
    {{- include "frontend-test.labels" . | nindent 4 }}
spec:
  serviceAccountName: {{ .Values.serviceAccount.name | default .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend-test
      {{- include "frontend-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:        
        app: frontend-test
        {{- include "frontend-test.selectorLabels" . | nindent 8 }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - frontend-test
              topologyKey: "kubernetes.io/hostname"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetport }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 5
            periodSeconds: 10
        
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.targetport }}
            initialDelaySeconds: 3
            periodSeconds: 5
