apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontend-test.fullname" . }}
  labels:
    {{- include "frontend-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: frontend-test
    {{- include "frontend-test.selectorLabels" . | nindent 4 }}
